CREATE TABLE
		REVIEW
		(
			ID UNSIGNED INT NOT NULL REFERENCES CUSTOMER(CUST_ID),
			REVIEW_ID UNSIGNED INT NOT NULL AUTO INCREMENT COMMENT 'review id',
			REVIEW_TITL VARCHAR(250) NOT NULL COMMENT 'review title',
			PRIMARY KEY(ID, REVIEW_ID)			
		);