CREATE TABLE
		CONTACT
		(
			USR_ID INT UNSIGNED NOT NULL REFERENCES USR(USR_ID),
			CNCT_ID VARCHAR(8)NOT NULL COMMENT 'contact id',
			CNCT_TYPE VARCHAR(10) COMMENT 'Type of Contact',
			CNCT_VAL VARCHAR(50) COMMENT 'Contact',
			PRIMARY KEY(USR_ID, CNCT_ID)
		);
		