CREATE TABLE
		COMMENT
		(
			ID UNSIGNED INT NOT NULL REFERENCES ORDR(ORDR_ID),
			COMMENT_ID VARCHAR(8)NOT NULL COMMENT 'Comment id',	
			COMMENT_TXT TEXT COMMENT 'Comment text',
			TS_CRT  TIMESTAMP NOT NULL COMMENT 'creation date',
			PRIMARY KEY(ID, CNCT_ID)
		);
		