CREATE TABLE
	CATALOG
	(
		CAT_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'catalog id sequence',
		CAT_DESC VARCHAR(200) COMMENT 'description of catalog',
		CAT_NM VARCHAR(100) NOT NULL COMMENT 'Catalog name',
		PRIMARY KEY (CAT_ID)
	);