CREATE TABLE
		ADDRESS
		(
			USR_ID INT UNSIGNED NOT NULL REFERENCES USR(USR_ID),
			ADDR_ID VARCHAR(2)NOT NULL COMMENT 'address id',
			ADDRESS_LINE_1 VARCHAR(100) COMMENT 'Address Line 1',
			ADDRESS_LINE_2 VARCHAR(100) COMMENT 'Address Line 2',
			ADDRESS_LINE_3 VARCHAR(100) COMMENT 'Address Line 3',
			CITY VARCHAR(100) COMMENT 'City',
			STATE VARCHAR(100) COMMENT 'State',
			POSTAL_CODE VARCHAR(10) COMMENT 'POSTAL CODE',
			PRIMARY KEY(USR_ID, ADDR_ID)
		);
