CREATE TABLE
	CATEGORY
	(
		CGY_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'category id sequence',
		CAT_ID INT  UNSIGNED NOT NULL REFERENCES CATALOG(CAT_ID),
		CGY_DESC VARCHAR(200) COMMENT 'description of category',
		CGY_NM VARCHAR(100) NOT NULL COMMENT 'category name',
		PRIMARY KEY (CGY_ID, CAT_ID)
	);